;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
         avy-goto-char
         chee/back-to-indentation-or-beginning
         puni-backward-delete-char
         puni-backward-kill-word
         puni-forward-delete-char
         puni-forward-kill-word
         puni-kill-line
         ))

(setq mc/cmds-to-run-once
      '(
         handle-switch-frame
         lsp-ui-doc--handle-mouse-movement
         pixel-scroll-precision
         ))
